"use client";
import { useRouter } from "next/navigation";

const fmt = (n: number) => Number(n || 0).toLocaleString("en-PK");

export default function SalarySlipView({ slip, embedded = false }: { slip: any; embedded?: boolean }) {
  const router = useRouter();
  const goBack = () => {
    // Go to whichever page the user came from (Salary generator vs Reports).
    if (typeof window !== "undefined" && window.history.length > 1) router.back();
    else router.push("/salary");
  };
  return (
    <div className="fade-up salary-slip-page">
      {!embedded && (
        <div className="no-print" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
          <button onClick={goBack} style={{ fontSize: 13, color: "var(--brand)", background: "transparent", border: "none", cursor: "pointer", padding: 0 }}>← Back</button>
          <button className="btn btn-primary" onClick={() => window.print()}>🖨 Save PDF</button>
        </div>
      )}

      <div className="print-page-bg salary-slip" style={{
        background: "#fff", maxWidth: 900, margin: "0 auto",
        fontFamily: "'Segoe UI', Arial, sans-serif", fontSize: 14, color: "#1a1a1a",
        border: "1px solid #ddd", borderRadius: 8, position: "relative",
      }}>
        {/* Letterhead with logo */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "18px 28px", borderBottom: "3px solid #A32D2D", borderRadius: "8px 8px 0 0", background: "#fff" }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img className="ss-logo" src="/logo.png" alt="Supreme Art" style={{ height: 130, width: "auto", maxWidth: 400, objectFit: "contain" }} />
          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: 28, fontWeight: 800, color: "#A32D2D", textTransform: "uppercase", letterSpacing: 1.4, lineHeight: 1.1 }}>Salary Slip</div>
            <div className="urdu" style={{ fontSize: 24, color: "#A32D2D", fontWeight: 600, marginTop: 6 }}>تنخواہ کی پرچی</div>
            <div style={{ fontSize: 12, color: "#777", marginTop: 6 }}>Supreme Art (Pvt.) Ltd. · HR Department</div>
          </div>
        </div>

        {/* Top meta */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, padding: "12px 24px", background: "#fafafa", borderBottom: "2px solid #A32D2D" }}>
          <MetaPill label="Employee ID" value={slip.employeeCode || "—"} />
          <MetaPill label="Month" value={slip.month} />
          <MetaPill label="Year" value={String(slip.year)} />
        </div>

        {/* Employee info */}
        <SectionHeader>Employee Information</SectionHeader>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", padding: "0 24px 4px" }}>
          <InfoRow label="Employee Name" value={slip.employeeName} />
          <InfoRow label="Department" value={slip.department} />
          <InfoRow label="Designation" value={slip.designation} />
          <InfoRow label="Generated By" value={slip.generatedBy} />
        </div>

        {/* Attendance */}
        <SectionHeader color="#2e6b4f">Attendance Summary</SectionHeader>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", padding: "0 24px 4px", background: "#f6fbf8" }}>
          <AttRow label="Days Present" value={slip.daysPresent} color="#15803D" />
          <AttRow label="Days Absent" value={slip.daysAbsent} color="#DC2626" />
          <AttRow label="Days on Leave" value={slip.daysLeave} color="#D97706" />
          <AttRow label="Week Offs" value={slip.weekOffs} color="#15803D" />
        </div>

        {/* Earnings · Not Deducted · Deductions */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 0, padding: "0 24px", marginTop: 12 }}>
          <div style={{ paddingRight: 8 }}>
            <PanelHeader bg="#2e6b4f">EARNINGS</PanelHeader>
            <Row label="Basic Salary" value={slip.basicSalary} />
            <Row label="Conveyance Allow." value={slip.conveyance} />
            <Row label="Overtime / Bonus" value={slip.overtime} />
            <TotalRow color="#2e6b4f" bg="#e8f4e8" label="GROSS EARNINGS" value={slip.grossEarnings} />
          </div>
          <div style={{ paddingLeft: 8, paddingRight: 8 }}>
            <PanelHeader bg="#185FA5">NOT DEDUCTED</PanelHeader>
            <Row label="ESSI" value={slip.essiContribution} />
            <Row label="EOBI Employer (5% × min wage)" value={slip.eobiEmployerContribution} />
            <Row label="Accommodation" value={slip.accommodation} />
            <Row label="Food" value={slip.food} />
            <TotalRow color="#185FA5" bg="#e6f1fb" label="TOTAL BENEFITS" value={slip.totalNotDeducted} />
          </div>
          <div style={{ paddingLeft: 8 }}>
            <PanelHeader bg="#A32D2D">DEDUCTIONS</PanelHeader>
            <Row label={`Income Tax (${slip.incomeTaxPercent}%)`} value={slip.incomeTax} />
            <Row label={`EOBI Employee (${slip.eobiEmployeePercent}%)`} value={slip.eobiEmployee} />
            <Row label="Absent Deduction" value={slip.absentDeduction} />
            <Row label="Other Deduction" value={slip.otherDeduction} />
            <TotalRow color="#A32D2D" bg="#fde8e8" label="TOTAL DEDUCTIONS" value={slip.totalDeductions} />
          </div>
        </div>

        {/* Net Pay */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", margin: "20px 24px 0", borderRadius: 6, overflow: "hidden" }}>
          <div style={{ background: "#7C1F1F", color: "#fff", padding: "18px 22px", fontWeight: 700, fontSize: 17, display: "flex", alignItems: "center", gap: 8 }}>
            💰 NET PAY (PKR)
          </div>
          <div style={{ background: "#A32D2D", color: "#fff", padding: "18px 22px", fontWeight: 800, fontSize: 28, textAlign: "center" }}>
            {fmt(slip.netPay)}
          </div>
        </div>

        {/* Signatures */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", padding: "40px 40px 18px", gap: 40, marginTop: 14 }}>
          <div>
            <div style={{ fontSize: 14, fontStyle: "italic" }}>Employee Signature: ________________________</div>
            <div style={{ fontSize: 14, marginTop: 22, fontStyle: "italic" }}>Name: ______________________</div>
          </div>
          <div>
            <div style={{ fontSize: 14, fontStyle: "italic" }}>Authorized Signatory: ________________________</div>
            <div style={{ fontSize: 14, marginTop: 22, fontStyle: "italic" }}>Name & Stamp: __________________</div>
          </div>
        </div>

        <div style={{ background: "#f5f5f5", borderTop: "1px solid #e0e0e0", padding: "10px 24px", textAlign: "center", fontSize: 12, color: "#888", borderRadius: "0 0 8px 8px" }}>
          ⚠ This is a computer-generated salary slip.
        </div>
      </div>

      <style>{`
        @media print {
          .no-print { display: none !important; }
          header { display: none !important; }
          main { padding: 0 !important; }
          body { background: #fff !important; }
        }
      `}</style>
    </div>
  );
}

function SectionHeader({ children, color = "#A32D2D" }: { children: React.ReactNode; color?: string }) {
  return (
    <div style={{ background: color, color: "#fff", fontWeight: 700, fontSize: 14, padding: "9px 24px", textAlign: "center", letterSpacing: 1, marginTop: 10 }}>
      {children}
    </div>
  );
}
function MetaPill({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ display: "flex", gap: 10, alignItems: "center", fontSize: 15 }}>
      <span style={{ fontWeight: 600 }}>{label}:</span>
      <span style={{ background: "#fff3cd", padding: "4px 16px", borderRadius: 4, fontWeight: 700, border: "1px solid #e0c96e", fontSize: 15 }}>{value}</span>
    </div>
  );
}
function InfoRow({ label, value }: { label: string; value: any }) {
  return (
    <div style={{ display: "flex", padding: "7px 0", borderBottom: "1px solid #f0f0f0" }}>
      <span style={{ fontWeight: 600, minWidth: 170, fontSize: 14 }}>{label}:</span>
      <span style={{ fontSize: 14 }}>{value || "—"}</span>
    </div>
  );
}
function AttRow({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", padding: "7px 0", borderBottom: "1px solid #eaf4ee" }}>
      <span style={{ fontWeight: 600, fontSize: 14 }}>{label}:</span>
      <span style={{ fontWeight: 700, color, fontSize: 15 }}>{value}</span>
    </div>
  );
}
function PanelHeader({ children, bg }: { children: React.ReactNode; bg: string }) {
  return (
    <div style={{ background: bg, color: "#fff", fontWeight: 700, fontSize: 14, padding: "9px 14px", textAlign: "center", borderRadius: 4, marginBottom: 5, letterSpacing: 1 }}>
      {children}
    </div>
  );
}
function Row({ label, value }: { label: string; value: number }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", padding: "7px 12px", borderBottom: "1px solid #f3f3f3", fontSize: 14 }}>
      <span>{label}</span>
      <span style={{ fontVariantNumeric: "tabular-nums" }}>{fmt(value)}</span>
    </div>
  );
}
function TotalRow({ label, value, color, bg }: { label: string; value: number; color: string; bg: string }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 14px", background: bg, borderRadius: 4, marginTop: 5, fontWeight: 700, fontSize: 15 }}>
      <span style={{ color }}>{label}</span>
      <span style={{ color }}>{fmt(value)}</span>
    </div>
  );
}
